name: Mark/close stale requested posts

on:
  schedule:
  - cron: "0 17 * * MON-FRI"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue is light on activity. Feel free to comment if you are inspired to write this blog post!'
        close-issue-message: 'Closing this issue due to inactivity. Feel free to reopen if you are inspired to write this blog post!'
        days-before-stale: 180
        skip-stale-pr-message: true
        only-labels: Requested Post
        operations-per-run: 100
